"""报表模块 — M3.4 adaptive report planning + visualization/layout policy."""

from backend.app.report.assembly import (
    KpiValue,
    SalesReportAssemblyError,
    SalesReportData,
    SalesReportDataAssembler,
    SalesReportSpecBuilder,
    SectionProjection,
    TrendPoint,
)
from backend.app.report.contracts import (
    REPORT_TEMPLATE_CONTRACTS,
    RequirementAvailability,
    SALES_REPORT_CONTRACT,
    ReportAvailabilityStatus,
    ReportContractError,
    ReportContractValidation,
    ReportContractValidator,
    ReportDataPlan,
    ReportDataPlanBuilder,
    ReportDataQuery,
    ReportMetadataContract,
    ReportQueryRequirement,
    ReportQueryShape,
    ReportSchemaObjectType,
    ReportSchemaRequirement,
    TemplateContract,
    TemplateSchemaBinding,
)
from backend.app.report.fixed import SalesReportRenderer
from backend.app.report.resources import (
    InMemoryReportRepository,
    LocalReportRepository,
    ReportArtifact,
    ReportNotFoundError,
    ReportRepository,
    ReportResourceError,
    ReportStorageError,
)

__all__ = [
    "KpiValue",
    "SalesReportAssemblyError",
    "SalesReportData",
    "SalesReportDataAssembler",
    "SalesReportSpecBuilder",
    "SectionProjection",
    "TrendPoint",
    "REPORT_TEMPLATE_CONTRACTS",
    "RequirementAvailability",
    "SALES_REPORT_CONTRACT",
    "ReportAvailabilityStatus",
    "ReportContractError",
    "ReportContractValidation",
    "ReportContractValidator",
    "ReportDataPlan",
    "ReportDataPlanBuilder",
    "ReportDataQuery",
    "ReportMetadataContract",
    "ReportQueryRequirement",
    "ReportQueryShape",
    "ReportSchemaObjectType",
    "ReportSchemaRequirement",
    "TemplateContract",
    "TemplateSchemaBinding",
    "SalesReportRenderer",
    "InMemoryReportRepository",
    "LocalReportRepository",
    "ReportArtifact",
    "ReportNotFoundError",
    "ReportRepository",
    "ReportResourceError",
    "ReportStorageError",
]
