"""M4.0 initial schema: conversations, work_memories, pending_clarifications, result_snapshots, report_artifacts

Revision ID: 42821213393c
Revises: 
Create Date: 2026-08-18 10:50:23.101349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42821213393c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(length=64), nullable=False, comment='UUIDv4 conversation identifier'),
    sa.Column('runtime_mode', sa.String(length=16), nullable=False, comment='mock | real'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC last-update timestamp'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sqlite_autoincrement=False
    )
    op.create_table('pending_clarifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_mode', sa.String(length=16), nullable=False),
    sa.Column('chain_id', sa.String(length=64), nullable=False, comment='澄清链唯一 ID'),
    sa.Column('semantic_model_key', sa.String(length=128), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False, comment='PendingClarificationContext full payload (JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_mode', 'conversation_id', name='uq_pending_clarifications_runtime_conv')
    )
    op.create_index(op.f('ix_pending_clarifications_conversation_id'), 'pending_clarifications', ['conversation_id'], unique=False)
    op.create_table('report_artifacts',
    sa.Column('report_id', sa.String(length=64), nullable=False, comment='rpt_<uuidhex>'),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('semantic_model_key', sa.String(length=128), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_mode', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 of stored HTML'),
    sa.Column('relative_path', sa.String(length=256), nullable=False, comment='local_state/reports/<report_id>.html'),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='ReportArtifact full payload (JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('report_id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_report_artifacts_conversation_id'), 'report_artifacts', ['conversation_id'], unique=False)
    op.create_table('result_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_mode', sa.String(length=16), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint_hash', sa.String(length=64), nullable=False, comment='SHA-256 request fingerprint'),
    sa.Column('terminal_state', sa.String(length=32), nullable=False),
    sa.Column('response_type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False, comment='TurnResultSnapshot full payload (JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_mode', 'request_id', name='uq_result_snapshots_runtime_request')
    )
    op.create_index(op.f('ix_result_snapshots_conversation_id'), 'result_snapshots', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_result_snapshots_request_id'), 'result_snapshots', ['request_id'], unique=False)
    op.create_table('work_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False, comment='幂等请求 ID'),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_mode', sa.String(length=16), nullable=False, comment='mock | real'),
    sa.Column('state_status', sa.String(length=16), nullable=False, comment='pending | committed | failed'),
    sa.Column('base_memory_version', sa.Integer(), nullable=False, comment='本轮开始时 committed 版本'),
    sa.Column('memory_version', sa.Integer(), nullable=False, comment='当前版本号'),
    sa.Column('semantic_model_key', sa.String(length=128), nullable=True),
    sa.Column('report_template_key', sa.String(length=64), nullable=True),
    sa.Column('current_intent', sa.String(length=64), nullable=True),
    sa.Column('analysis_goal', sa.String(length=512), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True, comment='StructuredWorkMemory full payload (JSON)'),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_stage', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_mode', 'request_id', name='uq_work_memories_runtime_request')
    )
    op.create_index(op.f('ix_work_memories_conversation_id'), 'work_memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_work_memories_request_id'), 'work_memories', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_memories_request_id'), table_name='work_memories')
    op.drop_index(op.f('ix_work_memories_conversation_id'), table_name='work_memories')
    op.drop_table('work_memories')
    op.drop_index(op.f('ix_result_snapshots_request_id'), table_name='result_snapshots')
    op.drop_index(op.f('ix_result_snapshots_conversation_id'), table_name='result_snapshots')
    op.drop_table('result_snapshots')
    op.drop_index(op.f('ix_report_artifacts_conversation_id'), table_name='report_artifacts')
    op.drop_table('report_artifacts')
    op.drop_index(op.f('ix_pending_clarifications_conversation_id'), table_name='pending_clarifications')
    op.drop_table('pending_clarifications')
    op.drop_table('conversations')
    # ### end Alembic commands ###
